import {
    Blocks,
    ChartSpline,
    Palette,
    Settings,
    ShoppingCart,
    Tag,
    User,
    UserRound,
    Image,
    ShoppingBasket,
    CreditCard,
    MapPin,
    ShieldUser,
    Truck,
    Store,
    Library,
    BookOpen,
    ClipboardMinus,
} from "lucide-react";
import React from "react";

export const iconMap = {
    users: <User size={16} />,
    orders: <ShoppingCart size={16} />,
    analytics: <ChartSpline size={16} />,
    content: <Image size={16} />,
    customers: <UserRound size={16} />,
    themes: <Palette size={16} />,
    plugins: <Blocks size={16} />,
    products: <Tag size={16} />,
    settings: <Settings size={16} />,
    media: <Image size={16} />,
    carts: <ShoppingBasket size={16} />,
    payments: <CreditCard size={16} />,
    locations: <MapPin size={16} />,
    admins: <ShieldUser size={16} />,
    shipping: <Truck size={16} />,
    shops: <Store size={16} />,
    collections: <Library size={16} />,
    pages: <BookOpen size={16} />,
    policies: <ClipboardMinus size={16} />,
};
